# Generated by Django 5.2.4 on 2025-08-24 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_remove_customuser_telefone"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="telefone",
            field=models.IntegerField(null=True, unique=True),
        ),
    ]
